version: '3.9'

services:
  reverseProxy:
    container_name: 'reverseProxy'
    image: node:16
    ports:
      - '3000:3000'
    working_dir: '/home/node/reverse-proxy'
    environment:
      - IS_DEV_MODE=$IS_DEV_MODE
    volumes:
      - './:/home/node/reverse-proxy'
    depends_on: 
      - redisDataBase

  redisDataBase:
    container_name: 'redisDataBase'
    image: redis:latest
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'    
    command: bash -c "redis-server /usr/local/etc/redis/redis.conf"