version: '3.9'

services:
  reverseProxy:
    container_name: 'reverseProxy'
    image: node:16
    ports:
      - '$REVERSE_PROXY_CONTAINER_PORT:80'
    working_dir: '/home/node/reverse-proxy'
    volumes:
      - './:/home/node/reverse-proxy'
    env_file:
      './.env'